Student id : 202318032

Name : Kruti Patel


Question 1: Block matrix multiplication

In [1]:
import numpy as np
import requests
from bs4 import BeautifulSoup
import csv
import time
import pandas as pd

In [2]:
def block_multiply(A, B, size_block):
    A = np.array(A)
    B = np.array(B)

    if A.shape[1] != B.shape[0]:
        raise ValueError("Invalid matrix dimensions")

    ans = np.zeros((A.shape[0], B.shape[1]))

    for i in range(0, A.shape[0], size_block):
        for j in range(0, B.shape[1], size_block):
            for k in range(0, A.shape[1], size_block):
                ans[i:i+size_block, j:j+size_block] += np.dot(
                    A[i:i+size_block, k:k+size_block], B[k:k+size_block, j:j+size_block]
                )

    return ans

A = [
    [1, 2, 4, 1],
    [1, 0, -1, -2],
    [2, -1, 3, 1],
    [1, 2, 3, 4]
]

B = [
    [-2, 2, -3, 3],
    [0, 1, -1, 2],
    [-2, -1, 0, 1],
    [4, 0, 1, 4]
]

size_block = 2

result = block_multiply(A, B, size_block)

print("Result of Block Matrix Multiplication:")
for row in result:
    print(row)


Result of Block Matrix Multiplication:
[-6.  0. -4. 15.]
[-8.  3. -5. -6.]
[-6.  0. -4. 11.]
[ 8.  1. -1. 26.]


Question 2:

Utilize any freely available API endpoint on Rapidapi to
generate a dataset.

In [3]:
url = "https://quotes15.p.rapidapi.com/quotes/random/"

headers = {
	"X-RapidAPI-Key": "4867072605msh999d0a34c323dd1p138d0djsn50fb22ee5567",
	"X-RapidAPI-Host": "quotes15.p.rapidapi.com"
}

response = requests.get(url, headers=headers)

print(response.json())


{'id': 1918932, 'originator': {'id': 222645, 'language_code': 'en', 'description': '', 'master_id': 14399, 'name': 'Sophie Scholl', 'url': 'https://quotepark.com/authors/sophie-scholl/'}, 'language_code': 'en', 'content': 'Stand up for what you believe in even if you are standing alone.', 'url': 'https://quotepark.com/quotes/1918932-sophie-scholl-stand-up-for-what-you-believe-in-even-if-you-are-s/', 'tags': ['believer', 'evening', 'stand', 'standing']}


Add generated data from API to CSV file.

In [4]:
num_quotes = 20
data = []

for _ in range(num_quotes):
    response = requests.get(url, headers=headers)

    if response.status_code == 200:
        # Append the quote to the data
        quote_data = response.json()
        data.append(quote_data)
        print(f"Quote added: {quote_data['content']}")
    else:
        print(f"Failed to fetch a quote. Status code: {response.status_code}")

    time.sleep(1)

# Convert the dataset to a DataFrame
df = pd.DataFrame(data)
csv_file_path = "quotes_data.csv"
df.to_csv(csv_file_path, index=False, encoding='utf-8')

print(f"Dataset generated and saved to {csv_file_path}.")

Quote added: He is half of my soul, as the poets say.
Quote added: Don't judge people on who they used to be. Allow them to be who they are. See them «now». Not «then». 
Quote added: Don't ever change yourself to impress someone. They should be impress that you don't change to please others
Quote added: Everyone thinks of changing the world, but no one thinks of changing himself.
Quote added: People see me and think I have lots of girlfriends, do I look like I have lots of girlfriends?
Quote added: We all have two lives. The second begins when you realize you only have one.
Quote added: In order to see the boundaries of the probabilities, need to try impossible.
Quote added: Love is the motto, love is the beginning, love is the source and love is everything that your heart shall crave for, in this world and the next.
Quote added: The sin which is unpardonable is knowingly and wilfully to reject truth, to fear knowledge lest that knowledge pander not to thy prejudices.
Quote added: Wait

Import CSV file.

In [5]:
quotes = pd.read_csv('quotes_data.csv')
quotes

id                                         originator language_code  \
0   1261770  {'id': 127542, 'language_code': 'en', 'descrip...            en   
1   1947632  {'id': 164902, 'language_code': 'en', 'descrip...            en   
2   2103256  {'id': 283607, 'language_code': 'en', 'descrip...            en   
3   1432150  {'id': 127568, 'language_code': 'en', 'descrip...            en   
4   2103266  {'id': 283607, 'language_code': 'en', 'descrip...            en   
5   1947634  {'id': 164902, 'language_code': 'en', 'descrip...            en   
6   2035045  {'id': 218173, 'language_code': 'en', 'descrip...            en   
7   2110991  {'id': 284126, 'language_code': 'en', 'descrip...            en   
8    966375  {'id': 127330, 'language_code': 'en', 'descrip...            en   
9   2111753  {'id': 284126, 'language_code': 'en', 'descrip...            en   
10   814496  {'id': 131079, 'language_code': 'en', 'descrip...            en   
11  1051645  {'id': 131108, 'language_code': 'en', 'descrip...            en   
12  1825561  {'id': 218988, 'language_code': 'en', 'descrip...            en   
13  1791921  {'id': 214553, 'language_code': 'en', 'descrip...            en   
14  1438019  {'id': 129929, 'language_code': 'en', 'descrip...            en   
15  1839806  {'id': 218593, 'language_code': 'en', 'descrip...            en   
16  2035045  {'id': 218173, 'language_code': 'en', 'descrip...            en   
17  2076075  {'id': 164804, 'language_code': 'en', 'descrip...            en   
18  1185319  {'id': 129394, 'language_code': 'en', 'descrip...            en   
19   884540  {'id': 128005, 'language_code': 'en', 'descrip...            en   

                                              content  \
0            He is half of my soul, as the poets say.   
1   Don't judge people on who they used to be. All...   
2   Don't ever change yourself to impress someone....   
3   Everyone thinks of changing the world, but no ...   
4   People see me and think I have lots of girlfri...   
5   We all have two lives. The second begins when ...   
6   In order to see the boundaries of the probabil...   
7   Love is the motto, love is the beginning, love...   
8   The sin which is unpardonable is knowingly and...   
9   Waiting to die in old age will not benefit any...   
10  We cannot be sure of having something to live ...   
11        Someday death will take us to another star.   
12  The objective of education reform is to creat ...   
13                                Love lives forever.   
14  Watch for phonies, keep your enemies close nig...   
15  The Tenczyn castle dates from the 14th century...   
16  In order to see the boundaries of the probabil...   
17  Let it go, you've got to forget about revenge....   
18                   I'm not perfect… But I'm enough.   
19  Some people want it to happen, some wish it wo...   

                                                  url  \
0   https://quotepark.com/quotes/1261770-madeline-...   
1   https://quotepark.com/quotes/1947632-tom-hiddl...   
2   https://quotepark.com/quotes/2103256-cornelius...   
3   https://quotepark.com/quotes/1432150-leo-tolst...   
4   https://quotepark.com/quotes/2103266-cornelius...   
5   https://quotepark.com/quotes/1947634-tom-hiddl...   
6   https://quotepark.com/quotes/2035045-mehmed-ii...   
7   https://quotepark.com/quotes/2110991-mwanandek...   
8   https://quotepark.com/quotes/966375-aleister-c...   
9   https://quotepark.com/quotes/2111753-mwanandek...   
10  https://quotepark.com/quotes/814496-ernesto-ch...   
11  https://quotepark.com/quotes/1051645-vincent-v...   
12  https://quotepark.com/quotes/1825561-sukavich-...   
13  https://quotepark.com/quotes/1791921-michael-j...   
14  https://quotepark.com/quotes/1438019-tupac-sha...   
15  https://quotepark.com/quotes/1839806-marek-zuk...   
16  https://quotepark.com/quotes/2035045-mehmed-ii...   
17  https://quotepark.com/quotes/2076075-hatake-ka...   
18  https://quotepark.com/quotes/1185319-carl-r

Selecting specific columns.

In [6]:
quotes = quotes[['content','url','tags']]

In [7]:
quotes.head()

content  \
0           He is half of my soul, as the poets say.   
1  Don't judge people on who they used to be. All...   
2  Don't ever change yourself to impress someone....   
3  Everyone thinks of changing the world, but no ...   
4  People see me and think I have lots of girlfri...   

                                                 url  \
0  https://quotepark.com/quotes/1261770-madeline-...   
1  https://quotepark.com/quotes/1947632-tom-hiddl...   
2  https://quotepark.com/quotes/2103256-cornelius...   
3  https://quotepark.com/quotes/1432150-leo-tolst...   
4  https://quotepark.com/quotes/2103266-cornelius...   

                                                tags  
0                           ['Soul', 'half', 'poet']  
1            ['People', 'allowance', 'judge', 'use']  
2  ['someone', 'impress', 'impression', 'other', ...  
3  ['Motivational', 'Deep', 'Success', 'Inspirati...  
4  ['girlfriend', 'Thinking', 'likeness', 'look',...

Question 3:

Construct a dataset by scraping a
website online. Utilize BeautifulSoup or any other suitable scraping library to extract all the
details of Amazon products and compile a dataset.

In [10]:
def extract_product_title(soup):
   title_element = soup.find("span", id="productTitle")
   if title_element:
       return title_element.text.strip()
   else:
       return ""

def extract_product_rating(soup):
    try:
        rating_tag = soup.find("i", attrs={'class': 'a-icon a-icon-star a-star-4-5'}).string.strip()

    except AttributeError:
        try:
            rating_tag = soup.find("span", attrs={'class': 'a-icon-alt'}).string.strip()
        except:
            rating_tag = ""

    return rating_tag
def extract_review_count(soup):
   review_count_element = soup.find("span", id="acrCustomerReviewText")
   if review_count_element:
       return review_count_element.string.strip()
   return ""

def extract_availability_status(soup):
   availability_element = soup.find("div", id="availability")
   if availability_element and availability_element.find("span").string:
       return availability_element.find("span").string.strip()
   else:
       return "Not Available"


In [12]:
search_url = "https://www.amazon.com/s?k=playstation+4&ref=nb_sb_noss_2"
headers = ({'User-Agent':'', 'Accept-Language': 'en-US, en;q=0.5'})

response = requests.get(search_url, headers=headers)
soup = BeautifulSoup(response.content, "html.parser")

product_data = {"title": [], "rating": [], "reviews": [], "availability": []}

product_links = soup.find_all("a", class_="a-link-normal s-underline-text s-underline-link-text s-link-style a-text-normal")
product_links = [link.get("href") for link in product_links]

for product_link in product_links:

       new_webpage = requests.get("https://www.amazon.com" + product_link, headers=headers)

       product_soup = BeautifulSoup(new_webpage.content, "html.parser")

       # Extract product details using provided functions
       product_data["title"].append(extract_product_title(product_soup))
       product_data["rating"].append(extract_product_rating(product_soup))
       product_data["reviews"].append(extract_review_count(product_soup))
       product_data["availability"].append(extract_availability_status(product_soup))

   # Create and clean DataFrame
df = pd.DataFrame.from_dict(product_data)
df['title'].replace('', np.nan, inplace=True)
df = df.dropna(subset=['title'])

df.to_csv("amazon_data.csv", header=True, index=False)
df

title              rating  \
0              Sony Playstation PS4 1TB Black Console  4.6 out of 5 stars   
1               PlayStation 4 500GB Console (Renewed)  4.1 out of 5 stars   
2    PlayStation 4 Slim 1TB Console - Black (Renewed)  4.1 out of 5 stars   
3   RPlay Play-Station 4 PS4 1TB Slim Edition Jet ...  4.0 out of 5 stars   
4   Sony PlayStation 4 Slim Limited Edition 1TB Ga...  4.3 out of 5 stars   
5   Sony PlayStation 4 Pro w/ Accessories, 1TB HDD...  4.1 out of 5 stars   
6   Playstation Sony 4, 500GB Slim System [CUH-221...  4.5 out of 5 stars   
7   PlayStation 4 Slim 500GB Console [Discontinued...  4.4 out of 5 stars   
8   PlayStation®4 Console – Call of Duty® Modern W...  4.5 out of 5 stars   
9   Hogwarts Legacy - PlayStation 4 | English | EU...  4.7 out of 5 stars   
10  PlayStation 4 500GB Uncharted: The Nathan Drak...  4.5 out of 5 stars   
11                     PlayStation 4 Slim 1TB Console  4.7 out of 5 stars   
12  2 Pack Wireless Controller for PS4/Pro/Slim Co...  4.0 out of 5 stars   
13  AceGamer Wireless Controller for PS4, Custom D...  4.2 out of 5 stars   
14  PS4 Controller Charger Dock Station,PS4 Contro...  4.7 out of 5 stars   

           reviews                         availability  
0    1,341 ratings                             In Stock  
1      952 ratings                             In Stock  
2    1,478 ratings                             In Stock  
3       32 ratings                             In Stock  
4    1,340 ratings                             In Stock  
5      794 ratings                             In Stock  
6      338 ratings   Only 3 left in stock - order soon.  
7    1,359 ratings   Only 1 left in stock - order soon.  
8       37 ratings                             In Stock  
9      528 ratings                             In Stock  
10     565 ratings   Only 2 left in stock - order soon.  
11  15,642 ratings  Only 19 left in stock - order soon.  
12     140 ratings                        Not Available  
13     222 ratings                        Not Available  
14   2,822 ratings                        Not Available